site_name: Aprendendo Redes de Computadores
site_url: https://aprendendo-redes.netlify.com
site_description: Aprenda Redes de Computadores e Internet
site_author: Claudio Haruyoshi Hirose
copyright: Copyright &copy; 2018 - Claudio Haruyoshi Hirose

theme:
  name: 'material'
  language: 'pt'
  logo:
    icon: 'cloud_done'
  palette:
    primary: 'red'
    accent: 'red'    
markdown_extensions:
        - admonition
        - codehilite:
                linenums: true
        - footnotes
        - meta
        - pymdownx.arithmatex
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.keys
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
                custom_fences:
                   - name: sequence
                     class: uml-sequence-diagram
                     format: !!python/name:pymdownx.superfences.fence_code_format
                   - name: flow
                     class: uml-flowchart
                     format: !!python/name:pymdownx.superfences.fence_code_format
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tilde
extra_javascript:
        - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
        - 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
        - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
        - 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'
        - 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'
        - 'extra-js/extra.js'
        - 'extra-js/mermaid.min.js'
extra_css:
        - 'extra-css/mermaid.neutral.css'        
        - 'extra-css/extra.css'
pages:
        - Home: index.md
        - Aula 01 - Introdução: aula-001/index.md
